const express=require("express");
const {getMonthlyIncomeData,deleteEntry,particularMonthData,getExpenseGraphData}=require("../controllers/MonthlyData");
const{validateSession}=require("../helper/utils.js");
const lastyearData=require("../controllers/YearlyData.js");
const {addEntry,getDailyData,getcurrDayData,getDailyExpense, updateEntry}=require("../controllers/dailyData");
const entryRoute=express.Router();
entryRoute.post("/addentry",validateSession,addEntry);
entryRoute.get("/currdayentries",validateSession,getcurrDayData);
entryRoute.get("/getdailydata",validateSession,getDailyData);
entryRoute.get("/:userId/getDailyExpense",validateSession,getDailyExpense);
entryRoute.get("/lastMonthData",validateSession,getMonthlyIncomeData);
entryRoute.get("/particularMonthData",validateSession,particularMonthData);
entryRoute.get("/lastYearData",validateSession,lastyearData);
entryRoute.delete("/deleteEntry",validateSession,deleteEntry);
entryRoute.get("/getGraphData",validateSession,getExpenseGraphData);
entryRoute.patch("/editEntry",validateSession,updateEntry);
module.exports=entryRoute;