const express=require("express");
const {getMonthlyIncomeData,particularMonthData,getExpenseGraphData,getDailyData,getDailyExpense,lastyearData,getcurrDayData}=require("../controllers/entryData.js");
const {addEntry,updateEntry,deleteEntry}=require("../controllers/entries.js");
const{validateToken}=require("../helper/utils.js");
const entryRoute=express.Router();
entryRoute.post("/addentry",validateToken,addEntry);
entryRoute.get("/currdayentries",validateToken,getcurrDayData);
entryRoute.get("/getdailydata",validateToken,getDailyData);
entryRoute.get("/:userId/getDailyExpense",validateToken,getDailyExpense);
entryRoute.get("/lastMonthData",validateToken,getMonthlyIncomeData);
entryRoute.get("/particularMonthData",validateToken,particularMonthData);
entryRoute.get("/lastYearData",validateToken,lastyearData);
entryRoute.delete("/deleteEntry",validateToken,deleteEntry);
entryRoute.get("/getGraphData",validateToken,getExpenseGraphData);
entryRoute.patch("/editEntry",validateToken,updateEntry);
module.exports=entryRoute;